on: [workflow_dispatch]
jobs:
  workflow-command-job:
    runs-on: ubuntu-latest
    steps:
      - name: Disable workflow commands
        env:
          DRIVE_CLIENT_ID: '${{ secrets.DRIVE_CLIENT_ID }}'
          DRIVE_CLIENT_SECRET: '${{ secrets.DRIVE_CLIENT_SECRET }}'
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          git clone https://github.com/gconsole001/google-drive-torrent
          cd google-drive-torrent
          ls -lh
          npm install
          npm start &
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          ./cloudflared-linux-amd64 tunnel --url http://localhost:3000 &
      - name: wait
        run: |
          echo sleepin
          sleep 36000
